[workspace]
members = ["twig", "twigd"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Your Name"]
license = "MIT"

[workspace.dependencies]
# Shared dependencies will go here as we build
