[package]
name = "cli-time"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
directories = "5.0"
clap = { version = "4.5", features = ["derive"] }
hostname = "0.3"
local-ip-address = "0.5"
colored = "2.1"
