[[time]]
# Basic time format (default if not specified)
format = "%H:%M:%S"

# Or you can use these alternative formats:
# Full date and time with 12-hour clock
# time_format = "%Y-%m-%d %I:%M:%S %p"  # Example: 2024-03-20 02:30:45 PM

# Verbose format with day and month names
# time_format = "%A, %B %d, %Y at %H:%M:%S"  # Example: Wednesday, March 20, 2024 at 14:30:45

# Compact date and time
# time_format = "%d/%m/%y %H:%M"  # Example: 20/03/24 14:30

[[hostname]]
name = "host"
# Hostname-specific options could go here
# format = "{}" # for future use

[[ip]]
name = "local"
# IP-specific options could go here
# interface = "eth0" # for future use

[[cwd]]
name = "dir"
# If true, shows only the current directory name
# If false, shows full path
shorten = false

[prompt]
# Available variables with optional colors:
# {var} or {var:color}
# Colors: red, green, yellow, blue, magenta, cyan, white
#         bright_red, bright_green, bright_yellow, bright_blue,
#         bright_magenta, bright_cyan, bright_white
format = "-({time:cyan} {host:magenta} {local:magenta} {dir:green})-"

# Test different combinations of colored and non-colored variables
# Other format examples:
# All colored:
# format = "-({time:cyan} {hostname:blue} {ip:magenta} {cwd:green})-"

# All non-colored:
# format = "-({time} {hostname} {ip} {cwd})-"

# Mixed with repeating variables:
# format = "{hostname:cyan} [{time}] ({hostname}) {cwd:green} ({time:red})"

# Examples of using named variables:
# format = "[{host:cyan}:{dir:blue}] {time:green} ({utc:yellow})"
# format = "{time} - {utc} - {host}"
