[[time]]
# Basic time format (default if not specified)
name = "datetime"
format = "%H:%M:%S"

[[time]]
# Basic time format (default if not specified)
name = "t"
format = "(%H:%M:%S)"

[[time]]
# Basic time format (default if not specified)
name = "tt"
format = "(%H:%M:%S)"


[[hostname]]
name = "host"
# Hostname-specific options could go here
# format = "{}" # for future use

[[ip]]
name = "ip"
# IP-specific options could go here
# interface = "lo"

[[cwd]]
name = "dir"
# If true, shows only the current directory name
# If false, shows full path
shorten = false

# Battery/Power configurations
[[power]]
name = "bat"
format = "{percentage}"  # Raw percentage number

[[power]]
name = "bat_pct"
format = "{percentage}%"  # Percentage with % symbol

[[power]]
name = "bat_status"
format = "{status}"  # Charging/Discharging/Full/Not charging/Unknown

[[power]]
name = "bat_time"
format = "{time_left}"  # Time remaining or time until full

[[power]]
name = "bat_power"
format = "{power_now}W"  # Current power consumption

[[power]]
name = "bat_energy"
format = "{energy_now}/{energy_full}Wh"  # Current and full energy

[[power]]
name = "bat_voltage"
format = "{voltage}V"  # Battery voltage

[[power]]
name = "bat_temp"
format = "{temperature}°C"  # Battery temperature

[[power]]
name = "bat_health"
format = "{capacity}% health"  # Battery health percentage

[[power]]
name = "bat_cycles"
format = "{cycle_count} cycles"  # Charge cycle count

[[power]]
name = "bat_tech"
format = "{technology}"  # Battery technology

[[power]]
name = "bat_info"
format = "{manufacturer} {model}"  # Manufacturer and model

[[power]]
name = "bat_serial"
format = "{serial}"  # Serial number

# Combined formats for different use cases
[[power]]
name = "bat_minimal"
format = "{percentage}% {status}"  # Example: "85% Charging"

[[power]]
name = "bat_basic"
format = "{percentage}% {status} ({time_left})"  # Example: "85% Charging (1:30)"

[[power]]
name = "bat_detailed"
format = "{status} {percentage}% {power_now}W {temperature}°C"  # Example: "Charging 85% 45W 35°C"

[[power]]
name = "bat_technical"
format = "{voltage}V {power_now}W"  # Example: "12.1V 45W"

[[power]]
name = "bat_health_info"
format = "{capacity}% health, {cycle_count} cycles, {technology}"  # Example: "94% health, 234 cycles, Li-ion"

[[power]]
name = "bat_full"
format = "{status} {percentage}% ({energy_now}/{energy_full}Wh) {power_now}W {temperature}°C"  # Most detailed format

[prompt]
# Available variables with optional formatting:
# {var} or {var:format} - For configured variables
# {$ENV_VAR} or {$ENV_VAR:format} - For environment variables
# {"text"} or {"text":format} - For literal text
#
# Format can be a comma-separated list of:
# Colors: red, green, yellow, blue, magenta, cyan, white
#         bright_red, bright_green, bright_yellow, bright_blue,
#         bright_magenta, bright_cyan, bright_white
# Styles: bold, italic, normal
#
# Examples:
# {"→":cyan,bold}         - Bold cyan arrow
# {"Warning":red,italic}  - Italic red text
# {time:green,bold}       - Bold green time
# {$USER:yellow,normal}   - Normal yellow username
format = """
{"→":cyan} {"normal"} {"bold":red,bold} {"italic":yellow,italic}
-({datetime:cyan} {t} {host:magenta} {ip:magenta} {dir:green} {$USER:yellow})- {bat_technical}
# """

# Or another example:
# format = '''
# ┌─[{time:cyan}] - [{host:magenta}]
# └─[{dir:green}] $'''

# Test different combinations of colored and non-colored variables
# Other format examples:
# All colored:
# format = "-({time:cyan} {hostname:blue} {ip:magenta} {cwd:green})-"

# All non-colored:
# format = "-({time} {hostname} {ip} {cwd})-"

# Mixed with repeating variables:
# format = "{hostname:cyan} [{time}] ({hostname}) {cwd:green} ({time:red})"

# Examples of using named variables:
# format = "[{host:cyan}:{dir:blue}] {time:green} ({utc:yellow})"
# format = "{time} - {utc} - {host}"

# Examples using environment variables:
# format = "[{$USER}@{host}] {time}"
# format = "{time} [{$PWD:blue}] {$SHELL:green}"
# format = "{$LANG} - {$TERM} - {time}"
