# Example configuration for twig prompt generator
#
# Variable Resolution Rules:
# 1. Implicit sections: Using {cwd} in template auto-creates [cwd] section
# 2. Default names: [hostname] without name field creates {hostname} variable
# 3. Custom names: [cwd] with name="mydir" creates {mydir} variable instead
#
# Variable Types:
# - Config variables: {time}, {hostname}, {cwd}
# - Git variables: {git_branch}, {git_tracking}, {git_status}, {git_elapsed}
# - Environment variables: {$USER}, {$HOME}, etc.
# - Literal text: {"@":yellow}
#
# Styling: {var:color} or {var:color,style}
# Colors: black, red, green, yellow, blue, magenta, cyan, white
#         bright_black, bright_red, etc.
# Styles: bold, italic, underline
#
# Conditional Spacing: Use ~ for spaces that only appear if the next variable exists
# Example: {cwd}~{git_branch} - space only appears when in a git repo

# Sections are created implicitly from template variables
# Uncomment to customize behavior:
#
# [time]
# format = "%H:%M:%S"  # default format
#
# [hostname]
# name = "host"  # use {host} instead of {hostname}
#
# [cwd]
# name = "dir"  # use {dir} instead of {cwd}

# Git Variables (all variables share 'git' prefix for auto-detection):
# - {git_branch} - current branch name (e.g., "main", "dev")
# - {git_tracking} - ahead/behind status (e.g., "(ahead.2)", "(behind.3)")
# - {git_status_clean} - clean status indicator (":✔") [green]
# - {git_status_staged} - staged files (":+N") [yellow]
# - {git_status_unstaged} - modified/untracked files (":+N") [red]
# - {git_elapsed} - time since last commit (e.g., ":2s", ":5m", ":17h")
# Note: Specify colors in template for proper shell formatting

# IP Address Variables (all variables share 'ip' prefix for auto-detection):
# - {ip_address} - IP address (IPv4 or IPv6, e.g., "192.168.1.100", "fe80::1")
# - {ip_interface} - Interface name (e.g., "eth0", "wlan0", "en0")
# - {ip_version} - IP version ("4" or "6")
# Note: Auto-detects primary interface by default
#
# Uncomment to customize:
# [ip]
# interface = "wlan0"    # Specify interface (default: auto-detect)
# prefer_ipv6 = false    # Prefer IPv6 over IPv4 (default: false)

# Battery Variables (all variables share 'battery' prefix for auto-detection):
# - {battery_percentage} - Battery percentage (e.g., "85%")
# - {battery_status} - Battery status ("Charging", "Discharging", "Full", "Empty")
# - {battery_power} - Power draw in watts (e.g., "+45.2W" charging, "-12.5W" discharging)
# - {battery_power_charging} - Power when charging (e.g., "+45.2W") - only set when charging
# - {battery_power_discharging} - Power when discharging (e.g., "-12.5W") - only set when discharging
# Note: Returns empty on desktops without batteries
#
# Tip: Use conditional spacing (~) with charging/discharging variables for automatic color:
#   {battery_power_charging:green}~{battery_power_discharging:yellow}
#   This shows green when charging, yellow when discharging!
#
# Uncomment to enable:
# [battery]

# Responsive Prompts - Automatic prompt switching based on terminal width
#
# Twig detects your terminal width and selects the appropriate prompt format:
# - format_wide: Used when terminal width >= width_threshold (default: 100)
# - format_narrow: Used when terminal width < width_threshold
# - format: Fallback/default format (always required)
# - width_threshold: Column threshold for switching (default: 100)
#
# Use cases:
# - Laptop: Narrow terminal → minimal prompt
# - Desktop: Wide terminal → full-featured prompt
# - tmux/split panes: Automatically adjusts to pane width
#
# Example responsive config:
# [prompt]
# # Wide terminal (>= 100 cols): Show everything
# format_wide = "{time} {hostname} {ip_address} {battery_percentage} {cwd} {git_branch}{git_status_clean}"
# # Narrow terminal (< 100 cols): Minimal
# format_narrow = "{cwd} {git_branch}"
# # Default/fallback
# format = "{cwd}"
# # Custom threshold (optional)
# width_threshold = 100

[prompt]
format = '''--({time:cyan} {hostname:yellow} {ip_address:yellow}~{battery_percentage:yellow}~{battery_power_charging:green}~{battery_power_discharging:yellow} {cwd:green}~{git_branch:magenta}{git_tracking:magenta}{git_status_clean:green}{git_status_staged:yellow}{git_status_unstaged:red}{git_elapsed:cyan})--
{"!":white,bold} '''
# Uncomment for responsive prompts:
# format_wide = '''--({time:cyan} {hostname:yellow} {ip_address:yellow}~{battery_percentage:yellow}~{battery_power_charging:green}~{battery_power_discharging:yellow} {cwd:green}~{git_branch:magenta}{git_tracking:magenta}{git_status_clean:green}{git_status_staged:yellow}{git_status_unstaged:red}{git_elapsed:cyan})--
# {"!":white,bold} '''
# format_narrow = '''{cwd:green}~{git_branch:magenta}{git_status_clean:green}{git_status_unstaged:red}
# {"!":white,bold} '''
# width_threshold = 100
