# Example configuration for twig prompt generator
#
# Variable Resolution Rules:
# 1. Implicit sections: Using {cwd} in template auto-creates [cwd] section
# 2. Default names: [hostname] without name field creates {hostname} variable
# 3. Custom names: [cwd] with name="mydir" creates {mydir} variable instead
#
# Variable Types:
# - Config variables: {time}, {hostname}, {cwd}
# - Git variables: {git_branch}, {git_tracking}, {git_status}, {git_elapsed}
# - Environment variables: {$USER}, {$HOME}, etc.
# - Literal text: {"@":yellow}
#
# Styling: {var:color} or {var:color,style}
# Colors: black, red, green, yellow, blue, magenta, cyan, white
#         bright_black, bright_red, etc.
# Styles: bold, italic, underline
#
# Conditional Spacing: Use ~ for spaces that only appear if the next variable exists
# Example: {cwd}~{git_branch} - space only appears when in a git repo

# Sections are created implicitly from template variables
# Uncomment to customize behavior:
#
# [time]
# format = "%H:%M:%S"  # default format
#
# [hostname]
# name = "host"  # use {host} instead of {hostname}
#
# [cwd]
# name = "dir"  # use {dir} instead of {cwd}

# Git Variables (all variables share 'git' prefix for auto-detection):
# - {git_branch} - current branch name (e.g., "main", "dev")
# - {git_tracking} - ahead/behind status (e.g., "(ahead.2)", "(behind.3)")
# - {git_status_clean} - clean status indicator (":✔") [green]
# - {git_status_staged} - staged files (":+N") [yellow]
# - {git_status_unstaged} - modified/untracked files (":+N") [red]
# - {git_elapsed} - time since last commit (e.g., ":2s", ":5m", ":17h")
# Note: Specify colors in template for proper shell formatting

[prompt]
format = '''--({time:cyan} {hostname:yellow} {cwd:green}~{git_branch:magenta}{git_tracking:magenta}{git_status_clean:green}{git_status_staged:yellow}{git_status_unstaged:red}{git_elapsed:dim})--
{"$":white,bold} '''
