[time]
format = "%H:%M:%S"

[hostname]

[cwd]

[prompt]
# Section names = variable names: {time}, {hostname}, {cwd}
# Environment variables: {$USER}, {$HOME}, etc.
format = '''{time:cyan} {$USER:bright_green,bold}@{hostname:magenta} {cwd:green}
{"$":white,bold} '''
