# Example configuration for twig prompt generator
#
# Variable Resolution Rules:
# 1. Implicit sections: Using {cwd} in template auto-creates [cwd] section
# 2. Default names: [hostname] without name field creates {hostname} variable
# 3. Custom names: [cwd] with name="mydir" creates {mydir} variable instead
#
# Variable Types:
# - Config variables: {time}, {hostname}, {cwd}
# - Git variables: {git_branch}, {git_tracking}, {git_status}, {git_elapsed}
# - Environment variables: {$USER}, {$HOME}, etc.
# - Literal text: {"@":yellow}
#
# Styling: {var:color} or {var:color,style}
# Colors: black, red, green, yellow, blue, magenta, cyan, white
#         bright_black, bright_red, etc.
# Styles: bold, italic, underline
#
# Conditional Spacing: Use ~ for spaces that only appear if the next variable exists
# Example: {cwd}~{git_branch} - space only appears when in a git repo

# Sections are created implicitly from template variables
# Uncomment to customize behavior:
#
# [time]
# format = "%H:%M:%S"  # default format
#
# [hostname]
# name = "host"  # use {host} instead of {hostname}
#
# [cwd]
# name = "dir"  # use {dir} instead of {cwd}

# Git Variables (all variables share 'git' prefix for auto-detection):
# - {git_branch} - current branch name (e.g., "main", "dev") [magenta]
# - {git_tracking} - ahead/behind status (e.g., "(ahead.2)", "(behind.3)") [magenta]
# - {git_status} - working tree status (":✔" clean, ":+N" for changes) [green/yellow]
# - {git_elapsed} - time since last commit (e.g., ":2s", ":5m", ":17h") [dim]
# Note: All git variables have built-in colors, no need to specify in template

[prompt]
format = '''--({time:cyan} {hostname:yellow} {cwd:green}~{git_branch}{git_tracking}{git_status}{git_elapsed})--
{"$":white,bold} '''
