[package]
name = "twigd"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
gethostname.workspace = true
serde.workspace = true
serde_json.workspace = true
directories.workspace = true
